apiVersion: v1
kind: Namespace
metadata:
  name: sock-shop

---
apiVersion: v1
kind: Service
metadata:
  name: front-end
  namespace: sock-shop
spec:
  selector:
    name: front-end
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8079

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end
  namespace: sock-shop
spec:
  replicas: 2
  selector:
    matchLabels:
      name: front-end
  template:
    metadata:
      labels:
        name: front-end
    spec:
      containers:
        - name: front-end
          image: weaveworksdemos/front-end:latest
          ports:
            - containerPort: 8079
